" -*- mode: vimrc -*-

set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

call vundle#end()            " required
filetype plugin indent on    " required

set number

set autoindent

set expandtab
set tabstop=4
set shiftwidth=4
